# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  push:
    # Pattern matched against refs/tags
    tags:
    # Push events to every tag not containing /
      - '*'           

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest
    env:
      CI: ''

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
          
      # install and build react 
      - name: Install React dependencies
        run: yarn install 
        working-directory: ./client
      - name: Build React App
        run: yarn build
        working-directory: ./client
        
      # install and build electron
      - name: Install Electron + nodejs dependencies
        run: yarn install
        working-directory: ./server
      - name: Build Electron App
        run: yarn dist-win
        working-directory: ./server
        
      # handle artifact
      - uses: actions/upload-artifact@v2
        with:
          name: wininstaller-64.exe
          path: ./server/dist/ontime-win64.exe

